---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aol-fss
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: aol-fss
  chart:
    git: git@github.com:tinytelly/full-stack
    path: applications/acurity/aol/aol
    ref: master
  values:
    #Remember an application needs to be able to support HA - you may get session issues as you switch from one server to another - k8s manages this in 'sessionAffinity: ClientIP' on a service.
    replicaCount: 1
    client: "fss"
    service:
      type: LoadBalancer
    image:
      repository: 34.75.134.151/docker/acurity-aol
      tag: 19.0.0
      pullPolicy: Always
