apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ops-CRB
  namespace: default
subjects:
  - kind: User
    name: matt.wood@mmc.com # AD User Name
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ops-CR # must match the name of the Role to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ops-CRB
  namespace: default
subjects:
  - kind: User
    name: peter.newnam@mmc.com # AD User Name
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ops-CR # must match the name of the Role to bind to
  apiGroup: rbac.authorization.k8s.io