apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ops-CR
  namespace: default
rules:
  - apiGroups: ["", "apps", "batch", "extensions"]
    resources: ["services", "endpoints", "pods", "secrets", "configmaps", "deployments", "jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]